USE healthy_diet_db;

SET FOREIGN_KEY_CHECKS = 0;
INSERT IGNORE INTO users (id, username, password_hash, role) VALUES (1010, '水尝无华', 'pwd_hash', 'USER');
INSERT IGNORE INTO user_profiles (user_id, nickname) VALUES (1010, '水尝无华');
INSERT INTO recipes (id, author_id, title, cover_image, status) VALUES (10, 1010, '蜜豆芝士皇冠花朵面包，颜值和味道双在线！', 'https://cp1.douguo.com/upload/caiku/6/a/4/800_6a91158347b4d12965fc348794e402f4.jpg', 'PUBLISHED');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 1, '步骤1                     准备好的部分原料。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 2, '步骤2                     面包粉，牛奶，酵母粉，鸡蛋全部倒厨师机揉面盆里。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 3, '步骤3                     用筷子搅成面絮，用厨师机揉出粗膜，放入软化的黄油、盐。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 4, '步骤4                     揉出手套膜。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 5, '步骤5                     密封醒十分钟。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 6, '步骤6                     分成一个160克的大面剂，剩下的面剂6等分，逐个揉圆。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 7, '步骤7                     取一个面剂捏成一圈薄中间厚的面片，放20克蜜豆，适量马苏里拉奶酪碎。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 8, '步骤8                     包严，接口压底下，依次包完 密封备用。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 9, '步骤9                     大面剂擀成比烤盘还大一点的薄面片。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 10, '步骤10                     烤盘铺油纸，中间倒扣一个小碗。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 11, '步骤11                     把薄面片盖碗上。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 12, '步骤12                     面包胚均匀的放一圈，压着面片。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 13, '步骤13                     如图从两个面包胚中间割开，把面片等分成六份。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 14, '步骤14                     逐个压面包胚上。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 15, '步骤15                     可以抹点水，促进粘合。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 16, '步骤16                     把碗取出。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 17, '步骤17                     放温暖处发酵1.5倍大，手指头轻按能弹起。刷蛋液，撒芝麻。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 18, '步骤18                     放入提前180度预热5分钟以上的烤箱中下层，烤25分钟左右，看状态出炉。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 19, '步骤19                     芝士蜜豆皇冠花朵面包蓬松喧软拉丝，组织细腻，麦香味足，蜜豆香甜软糯，芝士奶香味浓拉丝，出炉就吃了一个。 ​');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 20, '步骤20                     成品');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 21, '步骤21                     成品');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 22, '步骤22                     成品');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (10, 23, '步骤23                     蜜豆香甜软糯，芝士奶香味浓拉丝。 ​');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '面包粉', '300克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '牛奶', '190克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '酵母粉', '4克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '盐', '3克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '马苏里拉芝士', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (10, '蜜豆', '120克');

INSERT IGNORE INTO users (id, username, password_hash, role) VALUES (1011, '桃子很2', 'pwd_hash', 'USER');
INSERT IGNORE INTO user_profiles (user_id, nickname) VALUES (1011, '桃子很2');
INSERT INTO recipes (id, author_id, title, cover_image, status) VALUES (11, 1011, '非常简单雪人饼干（圣诞专属）', 'https://cp1.douguo.com/upload/caiku/5/1/d/800_5135c8589e5ed001c1e851098c768d7d.jpeg', 'PUBLISHED');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (11, 1, '步骤1                     黄油软化后加糖粉、蛋液打蛋器混匀');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (11, 2, '步骤2                     筛入可可粉和低筋面粉混合成面团');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (11, 3, '步骤3                     面团擀成3-4mm的薄片，冰箱冷冻15分钟，圆形模具切');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (11, 4, '步骤4                     蛋白霜预拌粉60g+15g水，打蛋器混匀后直接挤在饼干上');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (11, 5, '步骤5                     棉花糖做雪人头，用巧克力画眼睛嘴巴鼻子');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (11, 6, '步骤6                     放在饼干上画围巾就ok了，非常简单');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '黄油', '60克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '糖粉', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '全蛋液', '20克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '低筋面粉', '115克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '可可粉', '5克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '蛋白霜预拌粉', '60g');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '巧克力装饰', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '水', '15克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '黄油', '60克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '糖粉', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '全蛋液', '20克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '低筋面粉', '115克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '可可粉', '5克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '蛋白霜预拌粉', '60g');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '巧克力装饰', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '水', '15克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '黄油', '60克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '糖粉', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '全蛋液', '20克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '低筋面粉', '115克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '可可粉', '5克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '蛋白霜预拌粉', '60g');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '巧克力装饰', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '水', '15克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '黄油', '60克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '糖粉', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '全蛋液', '20克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '低筋面粉', '115克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '可可粉', '5克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '蛋白霜预拌粉', '60g');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '巧克力装饰', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '水', '15克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '黄油', '60克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '糖粉', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '全蛋液', '20克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '低筋面粉', '115克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '可可粉', '5克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '蛋白霜预拌粉', '60g');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '巧克力装饰', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '水', '15克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '黄油', '60克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '糖粉', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '全蛋液', '20克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '低筋面粉', '115克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '可可粉', '5克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '蛋白霜预拌粉', '60g');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '巧克力装饰', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (11, '水', '15克');

INSERT IGNORE INTO users (id, username, password_hash, role) VALUES (1012, '劉晓晓下厨房', 'pwd_hash', 'USER');
INSERT IGNORE INTO user_profiles (user_id, nickname) VALUES (1012, '劉晓晓下厨房');
INSERT INTO recipes (id, author_id, title, cover_image, status) VALUES (12, 1012, '0糖0油的燕麦可可饼干', 'https://cp1.douguo.com/upload/caiku/c/a/3/800_cac2a298c4c722fc3da0eaace99c4103.jpeg', 'PUBLISHED');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (12, 1, '步骤1                     准备200克燕麦片加20克可可粉。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (12, 2, '步骤2                     加两根香蕉一个鸡蛋来点代糖');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (12, 3, '步骤3                     按成小饼上空气炸锅');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (12, 4, '步骤4                     180度15-20分钟');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '燕麦', '200克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '可可粉', '20克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '香蕉', '2根');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '代糖', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '燕麦', '200克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '可可粉', '20克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '香蕉', '2根');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '代糖', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '燕麦', '200克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '可可粉', '20克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '香蕉', '2根');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '代糖', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '燕麦', '200克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '可可粉', '20克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '香蕉', '2根');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (12, '代糖', '1勺');

INSERT IGNORE INTO users (id, username, password_hash, role) VALUES (1013, '禾小荷', 'pwd_hash', 'USER');
INSERT IGNORE INTO user_profiles (user_id, nickname) VALUES (1013, '禾小荷');
INSERT INTO recipes (id, author_id, title, cover_image, status) VALUES (13, 1013, '芝士烤香蕉', 'https://cp1.douguo.com/upload/caiku/0/c/1/800_0cee7aaf7dc706349c177ccd1a7aacd1.jpg', 'PUBLISHED');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (13, 1, '步骤1                     食材。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (13, 2, '步骤2                     烤碗里刷一层融化的黄油，防粘而且增加奶香味。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (13, 3, '步骤3                     香蕉切块放入烤碗。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (13, 4, '步骤4                     鸡蛋牛奶混合倒入碗里，根据口味添加适量白糖。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (13, 5, '步骤5                     再撒上一层马苏里拉奶酪，');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (13, 6, '步骤6                     放入空气炸锅，200度烤15分钟。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (13, 7, '步骤7                     奶香浓郁。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (13, 8, '步骤8                     看着有食欲。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (13, 9, '步骤9                     超美味。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (13, 10, '步骤10                     安佳的奶酪和黄油都很不错。');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '香蕉', '一根');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳黄油', '5克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳马苏里拉芝士', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '牛奶', '100克毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '白砂糖', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '香蕉', '一根');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳黄油', '5克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳马苏里拉芝士', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '牛奶', '100克毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '白砂糖', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '香蕉', '一根');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳黄油', '5克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳马苏里拉芝士', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '牛奶', '100克毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '白砂糖', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '香蕉', '一根');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳黄油', '5克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳马苏里拉芝士', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '牛奶', '100克毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '白砂糖', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '香蕉', '一根');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳黄油', '5克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳马苏里拉芝士', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '牛奶', '100克毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '白砂糖', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '香蕉', '一根');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳黄油', '5克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳马苏里拉芝士', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '牛奶', '100克毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '白砂糖', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '香蕉', '一根');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳黄油', '5克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳马苏里拉芝士', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '牛奶', '100克毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '白砂糖', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '香蕉', '一根');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳黄油', '5克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳马苏里拉芝士', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '牛奶', '100克毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '白砂糖', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '香蕉', '一根');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳黄油', '5克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳马苏里拉芝士', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '牛奶', '100克毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '白砂糖', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '香蕉', '一根');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳黄油', '5克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '安佳马苏里拉芝士', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '牛奶', '100克毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (13, '白砂糖', '适量');

INSERT IGNORE INTO users (id, username, password_hash, role) VALUES (1014, '无我Jin', 'pwd_hash', 'USER');
INSERT IGNORE INTO user_profiles (user_id, nickname) VALUES (1014, '无我Jin');
INSERT INTO recipes (id, author_id, title, cover_image, status) VALUES (14, 1014, '太太乐糟粕醋火锅', 'https://cp1.douguo.com/upload/caiku/d/c/e/800_dc6f986d0551d6c9b852c4531983e15e.jpg', 'PUBLISHED');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (14, 1, '步骤1                     剪开有两小袋哦');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (14, 2, '步骤2                     倒入锅中');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (14, 3, '步骤3                     加水放入苹果片');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (14, 4, '步骤4                     准备调料');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (14, 5, '步骤5                     做好调料。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (14, 6, '步骤6                     菜洗好备用。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (14, 7, '步骤7                     热气腾腾煮起来');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (14, 8, '步骤8                     好吃，棒棒哒！');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '蒜蓉', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '小米辣', '青辣椒 适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '芝麻油，葱花，鸡精', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '沙茶酱', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '苹果片', '5片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '蒜蓉', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '小米辣', '青辣椒 适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '芝麻油，葱花，鸡精', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '沙茶酱', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '苹果片', '5片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '蒜蓉', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '小米辣', '青辣椒 适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '芝麻油，葱花，鸡精', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '沙茶酱', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '苹果片', '5片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '蒜蓉', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '小米辣', '青辣椒 适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '芝麻油，葱花，鸡精', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '沙茶酱', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '苹果片', '5片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '蒜蓉', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '小米辣', '青辣椒 适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '芝麻油，葱花，鸡精', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '沙茶酱', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '苹果片', '5片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '蒜蓉', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '小米辣', '青辣椒 适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '芝麻油，葱花，鸡精', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '沙茶酱', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '苹果片', '5片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '蒜蓉', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '小米辣', '青辣椒 适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '芝麻油，葱花，鸡精', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '沙茶酱', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '苹果片', '5片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '蒜蓉', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '小米辣', '青辣椒 适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '芝麻油，葱花，鸡精', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '沙茶酱', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (14, '苹果片', '5片');

INSERT IGNORE INTO users (id, username, password_hash, role) VALUES (1015, '窗边的小豆豆。', 'pwd_hash', 'USER');
INSERT IGNORE INTO user_profiles (user_id, nickname) VALUES (1015, '窗边的小豆豆。');
INSERT INTO recipes (id, author_id, title, cover_image, status) VALUES (15, 1015, '芝士芒果夹心奶油蛋糕', 'https://cp1.douguo.com/upload/caiku/8/d/9/800_8dc20955c865c7a2a7dc45648c465b79.jpeg', 'PUBLISHED');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 1, '步骤1                     准备食材：安佳原味黄油、安佳轻咸味芝士片、低筋面粉、鸡蛋、牛奶、白砂糖。（六寸戚风蛋糕可以做一个，四寸戚风蛋糕可以做两个）');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 2, '步骤2                     提前将安佳原味黄油隔热水融化备用。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 3, '步骤3                     将蛋白和蛋黄分离，分别放置两个空碗中备用。（蛋白的那个碗一定要无水无油保持干燥，不然影响蛋白打发），打发前可以先把蛋白放冰箱冷冻半小时更容易打发。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 4, '步骤4                     在蛋黄里倒入融化好的安佳黄油、牛奶混合搅拌均匀。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 5, '步骤5                     蛋黄液搅拌均匀。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 6, '步骤6                     加入过筛后的低筋面粉，用Z字搅拌的方式轻轻搅拌均匀。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 7, '步骤7                     蛋黄液搅拌至酸奶的流动状态。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 8, '步骤8                     将冷冻过的蛋白加几滴白醋（或者柠檬汁）分三次将白砂糖加入蛋白打发蛋白。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 9, '步骤9                     蛋白打发至打蛋器有阻力，停止转动后，蛋白有明显的纹路就可以了。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 10, '步骤10                     取三分一打好的蛋白，加入到搅拌好的蛋黄液里，用刮刀从下往上再从四周切拌均匀。搅拌好的蛋黄液体再全部倒入蛋白霜里，用切拌的方式搅拌均匀备用。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 11, '步骤11                     将搅拌均匀的蛋糕液体倒入模具内，倒入五分满后，放入1片安佳轻咸味芝士片，安佳轻咸芝士，创新风味，成就那一道点睛的流心瀑布。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 12, '步骤12                     安佳轻咸味芝士放入后，继续倒入蛋糕液，倒至模具的8-9分满，模具摔几下震出气孔。（两个四寸）');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 13, '步骤13                     烤箱150度预热10分钟后，上下火140度烤70分钟。（六寸可以做一个，四寸可以做两个）');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 14, '步骤14                     戚风蛋糕烤好后倒扣网格上放凉后脱模。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 15, '步骤15                     准备夹心蛋糕食材：芒果分别切大块（面上）、小块（夹心）、新鲜蓝莓、淡奶油200克加入20克白砂糖打发好装入裱花袋备用。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 16, '步骤16                     烤好的戚风蛋糕按照自己的喜好平均切成两等份或者三等分，抹上打发好的奶油。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 17, '步骤17                     在奶油上放入芒果粒和新鲜蓝莓，重复操作2-3次，取决于戚风蛋糕切两层还是三层。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 18, '步骤18                     最后撒上防潮糖霜即可。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 19, '步骤19                     成品图。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 20, '步骤20                     成品图。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (15, 21, '步骤21                     成品图。');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '芝士戚风蛋糕：', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳原味黄油', '30克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '安佳轻咸味芝士片', '2片');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '低筋面粉', '65克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '牛奶', '80毫升');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '鸡蛋', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '柠檬汁（白醋）', '几滴');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (15, '白砂糖', '30克');

INSERT IGNORE INTO users (id, username, password_hash, role) VALUES (1016, '寻找米米', 'pwd_hash', 'USER');
INSERT IGNORE INTO user_profiles (user_id, nickname) VALUES (1016, '寻找米米');
INSERT INTO recipes (id, author_id, title, cover_image, status) VALUES (16, 1016, '雪菜肉丝面这样做也太好吃吧！', 'https://cp1.douguo.com/upload/caiku/a/c/7/800_ac948204f8143953086dca219a453547.jpg', 'PUBLISHED');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (16, 1, '步骤1                     肉丝用油翻炒变色。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (16, 2, '步骤2                     加入雪菜茸炒香。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (16, 3, '步骤3                     倒入适量清水。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (16, 4, '步骤4                     水开放入面饼。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (16, 5, '步骤5                     加适量盐、酱油、蚝油、剁椒。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (16, 6, '步骤6                     大致拌匀。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (16, 7, '步骤7                     撒尖椒圈和香葱碎。');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '雪菜茸', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '鸡肉', '100克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '面饼', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '盐', '少许');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '酱油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '剁椒', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '蚝油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '雪菜茸', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '鸡肉', '100克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '面饼', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '盐', '少许');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '酱油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '剁椒', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '蚝油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '雪菜茸', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '鸡肉', '100克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '面饼', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '盐', '少许');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '酱油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '剁椒', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '蚝油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '雪菜茸', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '鸡肉', '100克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '面饼', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '盐', '少许');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '酱油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '剁椒', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '蚝油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '雪菜茸', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '鸡肉', '100克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '面饼', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '盐', '少许');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '酱油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '剁椒', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '蚝油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '雪菜茸', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '鸡肉', '100克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '面饼', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '盐', '少许');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '酱油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '剁椒', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '蚝油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '雪菜茸', '适量');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '鸡肉', '100克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '面饼', '1个');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '盐', '少许');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '酱油', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '剁椒', '1勺');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (16, '蚝油', '1勺');

INSERT IGNORE INTO users (id, username, password_hash, role) VALUES (1017, 'Angiecharm', 'pwd_hash', 'USER');
INSERT IGNORE INTO user_profiles (user_id, nickname) VALUES (1017, 'Angiecharm');
INSERT INTO recipes (id, author_id, title, cover_image, status) VALUES (17, 1017, '直接法全麦面包', 'https://cp1.douguo.com/upload/caiku/3/5/0/800_3592dedd097564d2366a4844e98ef1b0.jpeg', 'PUBLISHED');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (17, 1, '步骤1                     冷冻的鲜酵母和黄油先取出室温解冻。（替换成干酵母是5g）海盐、黄油、鲜酵母除外，其它食材全部放进搅拌缸。开启一档，搅拌至无干粉。开启三档，搅拌至粗略成团。加入鲜酵母，继续搅拌至全部吸收。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (17, 2, '步骤2                     加海盐，三档均匀后，转五档，直至面团呈光滑有弹性状态。加入切丁的黄油。先三档搅拌至完全吸收。转五档搅拌3分钟左右，至完全状态，能拉出坚韧薄膜。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (17, 3, '步骤3                     取出面团，整理一下表面，放进大烤盘里，稍压扁，放进密封的烤箱中，常温（23度）发酵大约50～60分钟。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (17, 4, '步骤4                     面团呈两倍大，按压有一点弹性。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (17, 5, '步骤5                     分割四等份。分别整理成圆面团，静置10分钟。分别擀开长条状。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (17, 6, '步骤6                     翻面后，往中间对折，掌心按压一下。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (17, 7, '步骤7                     擀卷后入模具。开启发酵模式，38度，湿度85左右。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (17, 8, '步骤8                     发酵约60分钟后，八分满。取出加上盖，预热烤箱，上火170，下火210。中层27分钟。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (17, 9, '步骤9                     出炉敲一下模具侧着倒出面包。');
INSERT INTO recipe_steps (recipe_id, step_number, instruction) VALUES (17, 10, '步骤10                     晾凉后切片。');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '全麦粉', '150克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '高筋面粉', '400克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '水', '360克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '细砂糖', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '鲜酵母', '15克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '盐', '7克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '黄油', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '全麦粉', '150克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '高筋面粉', '400克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '水', '360克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '细砂糖', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '鲜酵母', '15克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '盐', '7克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '黄油', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '全麦粉', '150克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '高筋面粉', '400克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '水', '360克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '细砂糖', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '鲜酵母', '15克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '盐', '7克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '黄油', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '全麦粉', '150克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '高筋面粉', '400克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '水', '360克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '细砂糖', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '鲜酵母', '15克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '盐', '7克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '黄油', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '全麦粉', '150克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '高筋面粉', '400克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '水', '360克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '细砂糖', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '鲜酵母', '15克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '盐', '7克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '黄油', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '全麦粉', '150克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '高筋面粉', '400克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '水', '360克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '细砂糖', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '鲜酵母', '15克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '盐', '7克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '黄油', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '全麦粉', '150克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '高筋面粉', '400克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '水', '360克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '细砂糖', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '鲜酵母', '15克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '盐', '7克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '黄油', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '全麦粉', '150克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '高筋面粉', '400克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '水', '360克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '细砂糖', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '鲜酵母', '15克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '盐', '7克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '黄油', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '全麦粉', '150克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '高筋面粉', '400克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '水', '360克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '细砂糖', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '鲜酵母', '15克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '盐', '7克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '黄油', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '全麦粉', '150克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '高筋面粉', '400克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '水', '360克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '细砂糖', '50克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '鲜酵母', '15克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '盐', '7克');
INSERT INTO recipe_ingredients (recipe_id, name, amount) VALUES (17, '黄油', '50克');

SET FOREIGN_KEY_CHECKS = 1;
